version: '3'
services:
  # Scenario:
  # Update zeckson/nginx Dockerfile
  # docker build -t zeckson/nginx .
  # docker-compose up
  # ? In this case docker-compose doesn't use latest image ?
  web:
    image: zeckson/nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx/yeticave.local.conf:/etc/nginx/conf.d/yeticave.local.conf
    - ./:/code
    networks:
    - code-network
  php:
    image: php:fpm
    volumes:
    - ./:/code
    networks:
    - code-network

networks:
  code-network:
    driver: bridge